# Travis-CI Build for libgit2sharp
# see travis-ci.org for details

language: csharp
dist: trusty
dotnet: 1.0.1
mono: none

os: linux

script:
 - dotnet restore test
 - dotnet build test/test.csproj -f netcoreapp1.0
 - dotnet test test/test.csproj -f netcoreapp1.0 --no-build

